% Solve a Pattern Recognition Problem with a Neural Network
% Script generated by NPRTOOL
% Created Sun Nov 30 17:31:08 BRST 2014
%

% Loads wineInputs and wineTargets
load wine_dataset.mat

inputs = wineInputs;
targets = wineTargets;

% Load a Pattern Recognition Network (Net)
load net

% Test the Network
outputs = net(inputs);
errors = gsubtract(targets,outputs);
performance = perform(net,targets,outputs)

% View the Network
view(net)

% Plots
figure, plotconfusion(targets,outputs)
figure, ploterrhist(errors)
